language: node_js
node_js:
  - "0.12"
deploy:
  provider: heroku
  api_key:
    secure: 8d8b31bf-ade7-46e9-a0e9-19c971785ad5
  app: frozen-coast-8956
  on:
    repo: luizfernandoalvesbraga/trabalhopi
